### ISSUE TITLE
FLBPluginExit() is not called when SIGINT is sent to the FB process

### ISSUE THREAD

**Issue by bgola-signalfx** [fluent/fluent-bit-go#22]
Reproduced on Fluent Bit 1.2.2 using `out_multiinstance` plugin. 

Simply add `log.Print("FLBPluginExit called")` to the `FLBPluginExit` and notice the message is not logged when FB is stopped.

**Comment by l2dy** [comment]
See https://github.com/fluent/fluent-bit/issues/1421, which is resolved in Fluent Bit v1.4.

**Comment by huzhou** [comment]
I don't think it is resolved. I am using fluent bit 1.4.2 and I add a log.Print("FLBPluginExit called") in FLBPluginExit. And I didn't see that

**Comment by huzhou** [comment]
Sorry, it is resolved. I can see it now

**Comment by cosmo0920** [comment]
Already done by https://github.com/fluent/fluent-bit/pull/1426.
