### ISSUE TITLE
FLBPluginSetContext violates Go 1.14's checkptr validation, fails under -race

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-bit-go#26]
I've noticed it with my fluent-bit-go-s3 plugin testing.
 
With Go tip (now Go 1.14 dev) and its new checkptr mode (enabled by default in -race mode):
full log is: https://travis-ci.org/cosmo0920/fluent-bit-go-s3/jobs/624006851#L246

```
--- FAIL: TestPluginInitializationWithSharedCredentials (0.00s)
panic: runtime error: unsafe pointer arithmetic [recovered]
	panic: runtime error: unsafe pointer arithmetic
goroutine 10 [running]:
testing.tRunner.func1(0xc0002dd320)
	/home/travis/.gimme/versions/go/src/testing/testing.go:916 +0xaeb
panic(0x10730e0, 0xc00000f9c0)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:967 +0x396
github.com/cosmo0920/fluent-bit-go-s3/vendor/github.com/fluent/fluent-bit-go/output.FLBPluginSetContext(...)
	/home/travis/gopath/src/github.com/cosmo0920/fluent-bit-go-s3/vendor/github.com/fluent/fluent-bit-go/output/output.go:76
github.com/cosmo0920/fluent-bit-go-s3.addS3Output(0x1c02bf0, 0x1, 0xc000000002)
	/home/travis/gopath/src/github.com/cosmo0920/fluent-bit-go-s3/out_s3.go:236 +0x271
github.com/cosmo0920/fluent-bit-go-s3.FLBPluginInit(0x1c02bf0, 0xd8)
	/home/travis/gopath/src/github.com/cosmo0920/fluent-bit-go-s3/out_s3.go:255 +0x55
github.com/cosmo0920/fluent-bit-go-s3.TestPluginInitializationWithSharedCredentials(0xc0002dd320)
	/home/travis/gopath/src/github.com/cosmo0920/fluent-bit-go-s3/out_s3_test.go:287 +0x480
testing.tRunner(0xc0002dd320, 0x1127ab0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:954 +0x1ec
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:1005 +0x661
exit status 2
FAIL	github.com/cosmo0920/fluent-bit-go-s3	0.039s
Makefile:26: recipe for target 'test' failed
make: *** [test] Error 1
The command "make" exited with 2.
```

**Comment by edsiper** [comment]
@cosmo0920 is this a breaking change on that Golang version ?, is there any workaround ?

cc: @wfernandes

**Comment by cosmo0920** [comment]
Yep, Go 1.14 testing module breaking changes.

**Comment by wfernandes** [comment]
@cosmo0920 Thanks for filing this issue. Apologies it took me so long to get to it. I'll take a look at this as soon as I can.

**Comment by wfernandes** [comment]
Also PRs are welcome if you'd like to contribute 😉

**Comment by wfernandes** [comment]
This issue seems to have some context what can be done to avoid this failure
https://github.com/google/go-cmp/issues/167

**Comment by l2dy** [comment]
Is this related to https://github.com/fluent/fluent-bit-go/issues/18#issuecomment-495489412?

**Comment by l2dy** [comment]
I have proposed a "correct" fix in #28, please help review and test it.

**Comment by l2dy** [comment]
@cosmo0920 Could you help check if the panic is fixed on master?

**Comment by cosmo0920** [comment]
Yes, will do.

**Comment by cosmo0920** [comment]
Your match can be working on https://travis-ci.com/github/cosmo0920/fluent-bit-go-s3/jobs/321439236.
With this patch: https://github.com/cosmo0920/fluent-bit-go-s3/commit/f45f7c169769146f71725742cf9591c4a63f1216

**Comment by wfernandes** [comment]
Seems like this is working. Thanks for your contributions. Apologies that it took so long.

**Comment by cosmo0920** [comment]
Yeah. We can close this.
Thanks for fixing. guys! 🤩
