### ISSUE TITLE
FLBPluginFlushCtx and FLBPluginFlush what's the difference between these two functions

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [fluent/fluent-bit-go#37]
FLBPluginFlushCtx and FLBPluginFlush what's the difference between these two functions?

When are the two functions called? If both functions exist in a plug-in, what is their calling relationship

**Comment by PettitWesley** [comment]
FLBPluginFlushCtx is called if both are defined. Only one will be called. They both serve the same purpose, they just have different signatures. FLBPluginFlushCtx takes a context argument that lets you store state between invocations.

**Comment by ZP-AlwaysWin** [comment]
> FLBPluginFlushCtx is called if both are defined. Only one will be called. They both serve the same purpose, they just have different signatures. FLBPluginFlushCtx takes a context argument that lets you store state between invocations.

ok,Thanks PettitWesley~
