### ISSUE TITLE
Is there a way to read config key with multiple times?

### ISSUE THREAD

**Issue by bin3377** [fluent/fluent-bit-go#47]
For example in the in-box [Prometheus Exporter](https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-exporter) output plugin, there can be more than one "add_label" in the config. Is there a way to read this kind of config with golang interface?

`FLBPluginConfigKey` seems only return a single string rather than an iterator or slice

**Comment by PettitWesley** [comment]
I think you probably have to implement some sort of special logic, like accept a string with commas as a delimitter and then split it.

**Comment by bin3377** [comment]
Thanks for the reply! But it makes very hard to pass a list of objects with few fields (probably can be in a json array but ugly). Hope it can be fixed someday.
