### ISSUE TITLE
Support for v0.12

### ISSUE THREAD

**Issue by guineveresaenger** [fluent/fluent-bit-go#6]
This plugin template currently only works for v0.11.x and lower.

It would be great to have it be compatible with v0.12.x.

**Comment by edsiper** [comment]
@guineveresaenger 

I've pushed a new branch called [api-0.12](https://github.com/fluent/fluent-bit-go/tree/api-0.12), that branch includes and enhanced version which also handle the new format type.

note that this is only compatible with Fluent Bit 0.12.x series. 

Please test it and send me some feedback

**Comment by edsiper** [comment]
cc: @adieu

**Comment by guineveresaenger** [comment]
Hurray! Will start working with this soon, and give feedback here. Thank you @edsiper!

**Comment by edsiper** [comment]
@guineveresaenger did you manage to test the new package ?

**Comment by guineveresaenger** [comment]
@edsiper it has been sitting in our backlog for the past week. We had to prioritize some other things first but will get there soon. Apologies for any delay. I'll make sure to let you know!

**Comment by edsiper** [comment]
Closing as fixed.
