### ISSUE TITLE
How to transform Record into a JSON string

### ISSUE THREAD

**Issue by Filirom1** [fluent/fluent-bit-go#7]
Hello,

I would like to create an output plugin for fluent-bit in go, but I down't know how to display the record  (map[interface {}]interface {}) into a JSON string.

Do you have any examples or links that could help me ?

Cheers
Romain

**Comment by Filirom1** [comment]
I am working on this plugin: https://github.com/Filirom1/fluent-bit-out-syslog

**Comment by edsiper** [comment]
the following block iterate and prints the record information in plain text, having that text format should not be hard to encode it in JSON format:

https://github.com/fluent/fluent-bit-go/blob/master/examples/out_gstdout/out_gstdout.go#L44

**Comment by majst01** [comment]
I wrote a redis output plugin:

see:
https://github.com/majst01/fluent-bit-go-redis-output/blob/master/out_redis.go#L83:L95
for reference.

**Comment by Filirom1** [comment]
Thank you @majst01
